setwd("~/ExploratoryDataAnalysis/ExData_Plotting1")
file<-"~/ExploratoryDataAnalysis/data/household_power_consumption.txt"
filedata<-read.table(file,header=T,sep=";",na.strings="?")
sub.filedata = subset(filedata, as.Date(Date, "%d/%m/%Y") >= as.Date('2007-02-01') & as.Date(Date, "%d/%m/%Y") <= as.Date('2007-02-02') )
rm(filedata)
sub.filedata$DateTime<-paste(sub.filedata$Date,sub.filedata$Time)
sub.filedata$DateTime<-strptime(sub.filedata$DateTime, "%d/%m/%Y %H:%M:%S")
png("plot3.png",width=480,height=480)
head(sub.filedata)
with(sub.filedata,plot(DateTime,Sub_metering_1, ylab="Energy sub metering",xlab="",type="n"))
with(sub.filedata,lines(DateTime,Sub_metering_1, col="black"))
with(sub.filedata,lines(DateTime,Sub_metering_2, col="red"))
with(sub.filedata,lines(DateTime,Sub_metering_3, col="blue"))
legend("topright", pch ="_", col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.off()
